name: Build, Test & Push
on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'  # all branches
  schedule:
    - cron: '0 0 * * *'  # every day at 0h

jobs:

  validateChangedFiles:
    # Generate condition: if file/s changed involve changes on the image, or trigger is cron
    name: "Conditional: files changed involve Docker image changes"
    runs-on: ubuntu-latest
    outputs:
      anyChanged: ${{ env.anyChanged }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      # Perform validation
      - name: Verify if any of the image-involved files changed
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          files: |
            .dockerignore
            Dockerfile
            tags.json
            tools/**
            scripts/**
      - name: Set environment variable for triggering next jobs
        if: ${{ steps.changed-files.outputs.any_changed == 'true' || github.event_name == 'schedule' }}
        run: echo "anyChanged=true" >> $GITHUB_ENV

  testBuild:
    # Run "build" tests
    name: Test (build)
    runs-on: ubuntu-latest
    if: ${{ needs.validateChangedFiles.outputs.anyChanged == 'true' }}
    needs:
      - validateChangedFiles

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        run: make test-install-requirements

      # Test
      - name: Test "build"
        run: make test-build


  tagsMatrix:
    # Parse and set the base_tag matrix to be used by following jobs
    name: Parse & Set tags matrix
    runs-on: ubuntu-latest
    if: ${{ needs.validateChangedFiles.outputs.anyChanged == 'true' }}
    needs:
      - validateChangedFiles
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Load & Set matrix variable
        id: set_matrix
        run: |
          TAGS=$(echo $(cat tags.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$TAGS"


  testNoBuild:
    # Run "no-build" tests (building image for linux/amd64)
    name: "[python:${{ matrix.base_tag }} Test (no-build)"
    runs-on: ubuntu-latest
    if: ${{ needs.validateChangedFiles.outputs.anyChanged == 'true' }}
    needs:
      - validateChangedFiles
      - testBuild
      - tagsMatrix
    strategy:
      fail-fast: false
      matrix:
        base_tag: ${{ fromJson(needs.tagsMatrix.outputs.matrix) }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        run: make test-install-requirements

      # Build
      - name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: "DockerPythonGitApp-docker-cache-${{ matrix.base_tag }}-{hash}"
          restore-keys: "DockerPythonGitApp-docker-cache-${{ matrix.base_tag }}"
      - name: Build
        run: make build BASE_TAG=${{ matrix.base_tag }}
      - name: Test "no-build" (arch=default)
        run: make test-nobuild
        env:
          IMAGE_TAG: ${{ matrix.base_tag }}


  build_push:
    # Build and push to DockerHub if current branch is "master"
    name: "[python:${{ matrix.base_tag }}] Build & Push (multiarch)"
    runs-on: ubuntu-latest
    if: ${{ needs.validateChangedFiles.outputs.anyChanged == 'true' && github.ref == 'refs/heads/master' }}
    needs:
      - validateChangedFiles
      - testBuild
      - testNoBuild
      - tagsMatrix
    strategy:
      fail-fast: false
      matrix:
        base_tag: ${{ fromJson(needs.tagsMatrix.outputs.matrix) }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Docker login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build & push for all archs
      - name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: "DockerPythonGitApp-docker-cache-${{ matrix.base_tag }}-{hash}"
          restore-keys: "DockerPythonGitApp-docker-cache-${{ matrix.base_tag }}"
      - name: Build & Push for all archs
        run: make buildx BASE_TAG=${{ matrix.base_tag }} ARCH=linux/amd64,linux/arm/v7
