name: Build, Test & Push
on:
  push: {}
  schedule:
    - cron: '0 0 * * *'  # every day at 0h

jobs:
  testBuild:
    # Run "build" tests
    name: Test (build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        run: make test-install-requirements
      - name: Test
        run: make test-build

  build_testNoBuild_push:
    # Build, run "no-build" tests, and push to DockerHub if current branch is "master"
    name: "[python:${{ matrix.base_tag }}/${{ matrix.arch }}] Build, Test (no-build) & Push"
    runs-on: ubuntu-latest
    needs: testBuild
    strategy:
      fail-fast: false
      matrix:
        base_tag:  # Same Docker tags than those used on the official Python image: https://hub.docker.com/_/python/
          - latest
          - slim
          - alpine
          - buster
          - 3.9-buster
          - 3.7.9-buster
          - 3.7.9-alpine
          - 3.8-buster
          - 3.5-slim-stretch
          - 3.6-slim-stretch
          - 3.7-slim-stretch
        arch:
          # "default" will use vanilla "docker build" (linux64) and run buildTests
          # "armv7" will use "docker buildx" (build and push on same step) and not run buildTests
          - default
          - armv7

    steps:
      # Preparation
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        if: matrix.arch == 'default'
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        if: matrix.arch == 'default'
        run: make test-install-requirements
      - name: Install QEMU
        if: matrix.arch == 'armv7'
        uses: docker/setup-qemu-action@v1
      - name: Install Docker Buildx
        if: matrix.arch == 'armv7'
        uses: docker/setup-buildx-action@v1

      # Docker login
      - name: Login to DockerHub
        # if: github.ref == 'refs/heads/master'  # TODO uncomment
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build image
      - name: Build (arch=default)
        if: matrix.arch == 'default'
        run: make build BASE_TAG=${{ matrix.base_tag }}
      - name: Build & Push (arch=armv7)
        if: matrix.arch == 'armv7' # && github.ref == 'refs/heads/master'  # TODO uncomment
        run: make buildx BASE_TAG=${{ matrix.base_tag }} ARCH=linux/arm/v7

      # Test no-build, with built image (default arch)
      - name: Test (arch=default)
        if: matrix.arch == 'default'
        run: make test-nobuild
        env:
          IMAGE_TAG: ${{ matrix.base_tag }}

      # Push build image to DockerHub (default arch)
      - name: Publish to DockerHub (arch=default)
        if: github.ref == 'refs/heads/master'
        run: make push BASE_TAG=${{ matrix.base_tag }}
