name: Build, Test & Push
on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'  # all branches
  schedule:
    - cron: '22 2 * * *'  # everyday at 02:22h

jobs:

  flagTestBuild:
    # Generate condition: if file/s changed involve changes on the image, or trigger is cron: test & build jobs must run
    name: "Conditional: run test & build jobs"
    runs-on: ubuntu-latest
    outputs:
      flag: ${{ env.flag }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      # Perform validation
      - name: Verify if any of the image-involved files changed
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          files: |
            .dockerignore
            Dockerfile
            images.json
            tools/**
            scripts/**
      - name: Set flag for triggering test & build jobs
        if: ${{ steps.changed-files.outputs.any_changed == 'true' || github.event_name == 'schedule' }}
        run: echo "flag=true" >> $GITHUB_ENV

  testBuild:
    # Run "build" tests
    name: Test (build)
    runs-on: ubuntu-latest
    if: ${{ needs.flagTestBuild.outputs.flag == 'true' }}
    needs:
      - flagTestBuild

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        run: make test-install-requirements

      # Test
      - name: Test "build"
        run: make test-build


  imagesMatrix:
    # Parse and set the images & archs matrix to be used by following jobs
    name: Parse & Set images matrix
    runs-on: ubuntu-latest
    if: ${{ needs.flagTestBuild.outputs.flag == 'true' }}
    needs:
      - flagTestBuild
    outputs:
      images: ${{ steps.set_matrix.outputs.images }}
      archs: ${{ steps.set_matrix.outputs.archs }}
    env:
      # for set_matrix script
      IMAGES_FILE: images.json
      OUTPUT_IMAGES_KEY: images
      OUTPUT_ARCHS_KEY: archs

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      # Export matrix variables
      - name: Load & Set matrix variables
        id: set_matrix
        run: python .github/workflows/scripts/build_test_push/set_matrix.py


  testNoBuild:
    # Run "no-build" tests (pre-building image for linux/amd64, only for images supporting this arch)
    name: "[${{ matrix.image.fromImage }} (${{ env.prebuildImageArch }})] Test (no-build)"
    runs-on: ubuntu-latest
    if: ${{ needs.flagTestBuild.outputs.flag == 'true' }}
    needs:
      - flagTestBuild
      - testBuild
      - imagesMatrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.imagesMatrix.outputs.images) }}
    env:
      prebuildImageArch: linux/amd64

    steps:
      # Condition
      - name: Determine if job must run
        run: |
          JSON_FILE=/tmp/matrix.image.arch.json
          echo '${{ toJson(matrix.image.archs) }}' > $JSON_FILE
          r=$( jq 'contains(["${{ env.prebuildImageArch }}"])' $JSON_FILE )
          echo "runFlag=$r" >> $GITHUB_ENV

      # Setup
      - name: Checkout
        if: ${{ env.runFlag == 'true' }}
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        if: ${{ env.runFlag == 'true' }}
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        if: ${{ env.runFlag == 'true' }}
        run: make test-install-requirements
      - name: Set environment variables
        if: ${{ env.runFlag == 'true' }}
        run: |
          echo "fromImage=${{ matrix.image.fromImage }}" >> $GITHUB_ENV
          echo "toImage=python-git-app:${{ matrix.image.toTag }}" >> $GITHUB_ENV

      # Build
      - name: Build
        if: ${{ env.runFlag == 'true' }}
        run: make build FROM_IMAGE=${{ env.fromImage }} TO_IMAGE=${{ env.toImage }}
      - name: Test "no-build" (arch=default)
        if: ${{ env.runFlag == 'true' }}
        run: make test-nobuild FROM_IMAGE=${{ env.toImage }}


  buildPush:
    # Build image, then push to DockerHub if current branch is "master"
    name: "[${{ matrix.image.fromImage }} -> ${{ matrix.image.toTag }} (${{ matrix.arch }})] Build & Push"
    runs-on: ubuntu-latest
    if: ${{ needs.flagTestBuild.outputs.flag == 'true' }}
    needs:
      - flagTestBuild
      - testBuild
      - testNoBuild
      - imagesMatrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.imagesMatrix.outputs.images) }}
        arch: ${{ fromJson(needs.imagesMatrix.outputs.archs) }}

    steps:
      # Condition
      - name: Determine if job must run
        run: |
          JSON_FILE=/tmp/matrix.image.arch.json
          echo '${{ toJson(matrix.image.archs) }}' > $JSON_FILE
          r=$( jq 'contains(["${{ matrix.arch }}"])' $JSON_FILE )
          echo "runFlag=$r" >> $GITHUB_ENV
      - name: Determine if install QEMU
        if: ${{ env.runFlag == 'true' }}
        run: |
          if [[ "${{ matrix.arch }}" != "linux/amd64" ]]
          then
            echo "qemuFlag=true" >> $GITHUB_ENV
          fi
      - name: Determine if must push built image
        if: ${{ github.ref == 'refs/heads/master' && env.runFlag == 'true' }}
        run: |
          echo "pushFlag=true >> $GITHUB_ENV"

      # Setup
      - name: Checkout
        if: ${{ env.runFlag == 'true' }}
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install QEMU
        if: ${{ env.runFlag == 'true' && env.qemuFlag == 'true' }}
        uses: docker/setup-qemu-action@v1
      - name: Install Docker Buildx
        if: ${{ env.runFlag == 'true' }}
        uses: docker/setup-buildx-action@v1
      - name: Set environment variables
        if: ${{ env.runFlag == 'true' }}
        run: |
          echo "fromImage=${{ matrix.image.fromImage }}" >> $GITHUB_ENV
          echo "toTag=${{ matrix.image.toTag }}" >> $GITHUB_ENV
          echo "arch=${{ matrix.image.arch }}" >> $GITHUB_ENV
          echo "buildxPush=false" >> $GITHUB_ENV
          if [[ '${{ env.pushFlag }}' == 'true' ]]
          then
            echo "buildxPush=true" >> $GITHUB_ENV
          fi

      # Docker login
      - name: Login to DockerHub
        if: ${{ env.runFlag == 'true' && env.buildxPush == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build/Push
      - name: Build & Push for all archs
        if: ${{ env.runFlag == 'true' }}
        run: make buildx FROM_IMAGE=${{ env.fromImage }} TO_TAG=${{ env.toTag }} BUILDX_PUSH=${{ env.buildxPush }} ARCH=${{ env.arch }}
