# Build, test (except "build" tests), and push the image with all the tags defined.
# This is intended to run for each push, except the Push to DockerHub last step, which shall run
# only in "master" branch, and scheduled to keep the images updated.

name: Build, Test & Push
on:
  push: {}
  schedule:
    - cron: '0 0 * * *'  # every day at 0h

jobs:
  build_test_push:
    name: Build, Test & Push (with python:${{ matrix.base_tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_tag:  # Same Docker tags than those used on the official Python image: https://hub.docker.com/_/python/
          - latest
          - slim
          - alpine
          - buster
          - 3.9-buster
          - 3.7.9-buster
          - 3.7.9-alpine
          - 3.8-buster
          - 3.5-slim-stretch
          - 3.6-slim-stretch
          - 3.7-slim-stretch
          - 2-slim-stretch

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        run: make test-install-requirements
      - name: Build
        run: make build
        env:
          BASE_TAG: ${{ matrix.base_tag }}
      - name: Test
        run: make test-nobuild
      - name: Publish to DockerHub
        run: make push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}