# Run "build" tests on each push

name: Test "build"
on:
  - push

jobs:
  test_build:
    name: Test image building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install test requirements
        run: make test-install-requirements
      - name: Test
        run: make test-build
